unit Model.Cadastro;

interface

uses MVCFramework.ActiveRecord;

type
  [MVCTable('cadastro')]
  [MVCEntityActions([eaCreate, eaRetrieve, eaUpdate, eaDelete])]
  TCadastro = class (TMVCActiveRecord)
  private
    [MVCTableField('codigo', [foPrimaryKey, foAutoGenerated])]
    FCodigo: Integer;
    [MVCTableField('cpf')]
    FCpf: string;
    [MVCTableField('nome')]
    FNome: string;
    procedure SetCodigo(const Value: Integer);
    procedure SetCpf(const Value: string);
    procedure SetNome(const Value: string);
    function GetCodigo: Integer;
    function GetCpf: string;
    function GetNome: string;

  public
    property Codigo: Integer read GetCodigo write SetCodigo;
    property Nome: string read GetNome write SetNome;
    property Cpf: string read GetCpf write SetCpf;
  end;

implementation

{ TCadastro }

function TCadastro.GetCodigo: Integer;
begin
 Result := FCodigo;
end;

function TCadastro.GetCpf: string;
begin
 Result := FCpf;
end;

function TCadastro.GetNome: string;
begin
 Result := FNome;
end;

procedure TCadastro.SetCodigo(const Value: Integer);
begin
  FCodigo := Value;
end;

procedure TCadastro.SetCpf(const Value: string);
begin
  FCpf := Value;
end;

procedure TCadastro.SetNome(const Value: string);
begin
  FNome := Value;
end;

initialization

  ActiveRecordMappingRegistry.AddEntity('cadastro', TCadastro);

finalization

end.
